plugins {
    id 'java'
    id 'idea'
    id 'eclipse'
    id 'maven-publish'
    id 'net.minecraftforge.gradle' version '[7.0.17,8)'
}

base {
    archivesName = 'Sus_InstantSwap-1.2.1-Forge26.1'
}

version = '1.2.1'
group = 'com.susinstantswap'

// Mojang ships Java 25 for 26.1+
java.toolchain.languageVersion = JavaLanguageVersion.of(25)

minecraft {
    runs {
        configureEach {
            workingDir = layout.projectDirectory.dir('run')

            systemProperty 'eventbus.api.strictRuntimeChecks', 'true'
            systemProperty 'forge.enabledGameTestNamespaces', 'susinstantswap'
        }

        register('client')

        register('server') {
            args '--nogui'
        }
    }
}

repositories {
    minecraft.mavenizer(it)
    maven fg.forgeMaven
    maven fg.minecraftLibsMaven
    mavenCentral()
    maven { url = 'https://maven.aliyun.com/repository/public/' }
    maven { url = 'https://mirrors.cloud.tencent.com/nexus/repository/maven-public/' }
}

dependencies {
    implementation minecraft.dependency('net.minecraftforge:forge:26.1-62.0.9')
    annotationProcessor 'net.minecraftforge:eventbus-validator:7.0.1'
}

tasks.named('processResources', ProcessResources).configure {
    var replaceProperties = [
            minecraft_version: '26.1',
            forge_version: '62.0.9',
            mod_id: 'susinstantswap',
            mod_version: '1.2.1',
    ]
    inputs.properties replaceProperties
    filesMatching(['META-INF/mods.toml']) {
        expand replaceProperties
    }
}

tasks.named('jar', Jar).configure {
    archiveVersion = ''
    manifest {
        attributes([
                'Specification-Title'     : 'susinstantswap',
                'Specification-Version'   : '1.2.1',
                'Implementation-Title'    : "Su's Instant Swap",
                'Implementation-Version'  : '1.2.1',
        ])
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
