# v2.0.1 - Sus_InstantSwap Forge 26.1
org.gradle.jvmargs=-Xmx3G -Dhttps.protocols=TLSv1.2,TLSv1.3
org.gradle.daemon=false

org.gradle.caching=true
org.gradle.parallel=true
org.gradle.configureondemand=true

org.gradle.configuration-cache=false
org.gradle.configuration-cache.parallel=true
org.gradle.configuration-cache.problems=warn

mod_version=2.0.1
net.minecraftforge.gradle.merge-source-sets=true
