modLoader="javafml"
loaderVersion="[1,)"
license="LGPL-3.0"

[[mods]]
modId="susinstantswap"
side="CLIENT"
version="${mod_version}"
displayName="Su's Instant Swap"
logoFile="assets/susinstantswap/icon.png"
authors="Su_Crispy"
description="Hold a key to open your inventory; release over a slot to instantly swap it with your hotbar selection. Supports long/short press dual modes, GUI swap, survival/creative/adventure game modes."

[[dependencies.susinstantswap]]
    modId="forge"
    mandatory=true
    versionRange="[62,65)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.susinstantswap]]
    modId="minecraft"
    mandatory=true
    versionRange="[26.1,26.2)"
    ordering="NONE"
    side="CLIENT"
